<a href="https://colab.research.google.com/github/booluckgmie/training/blob/main/Suggestion_Keywords_by_Category_using_Google_Trends_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Google Trends API for Python

## In this tutorial, I will demonstrate how to use the Google Trends API for getting the current trending <b>(1 week period)</b>: 

*   ## <b>top/rising keywords</b> 
*   ## <b>top/rising <u>related</u> keywords*</b>

## by <b>category</b> on the internet in Malaysia.


![alt text](https://cdn-images-1.medium.com/max/1200/1*Fi6masemXJT3Q8YWekQCDQ.png)

# Introduction

[Google trends](https://trends.google.com/trends/?geo=US) is a website that analyzes and lists the popular search results on Google search based on various regions and languages. Google Trends is Google's website (obviously). With the help of this tutorial, you can get the trending results and many more from google trends website using python. You don't need to manually search and copy the trending results, the Python API called `pytrends` does the job for you. Before getting started, I want all of you guys to go through the official documentation of the `pytrends` API.

[pytrends API](https://pypi.org/project/pytrends/)



---

# Installation

The first step is to install the library manually. So, open your favorite IDE or notebook start typing the following code. I will use [Google Colab](https://colab.research.google.com/) because it's my favorite notebook.



> If you are using jupyter notebook, just type the code as it is (make sure you have '!' at the beginning)

In [ ]:
!pip install pytrends -qq

  Building wheel for pytrends (setup.py) ... done



---

## Related Queries

It's a common thing that when a user searches for a topic, they would also search for something related. These are called related queries. Let us see what are the related queries for the topic "***Coronavirus***". Always remember when you want to change the topic name just run the following code again with the new name as the parameter.

In [ ]:
import pandas as pd
from pytrends.request import TrendReq

In [ ]:
pytrend = TrendReq(hl='en-US', tz=360)

In [ ]:
# Create payload and capture API tokens. Only needed for interest_over_time(), interest_by_region() & related_queries()trendy_keywords = ‘Data Science’
kw_list = [''] #let it blank for keyword
#kw = trendy_keywords
pytrend.build_payload(kw_list, cat=184, #Business & Industrial: 12;Law & Government: 19; Jobs & Education: 958; Movies: 34; Autos & Vehicles: 47 ; Vehicle Brands: 815
                           timeframe='2022-07-01 2022-08-08', geo='MY', gprop='') #timeframe='now 7-d' (too short API cannot find); timeframe by Specific dates, '2016-12-14 2017-01-25'

Category listing ==> https://github.com/pat310/google-trends-api/wiki/Google-Trends-Categories

Google-Trends API ==> https://github.com/GeneralMills/pytrends#trending-searches

In [ ]:
# Related Queries, returns a dictionary of dataframes
related_queries_dict = pytrend.related_queries()
#print(related_queries_dict)
rqueries = pd.DataFrame(related_queries_dict)
top = rqueries['']['top']
rising = rqueries['']['rising']

top.style.set_table_attributes("style='display:inline'").set_caption('Top Trending Keywords Table')

In [ ]:
rising.style.set_table_attributes("style='display:inline'").set_caption('Rising Keywords Table')

In [ ]:
# Related Topics, returns a dictionary of dataframes
related_topic = pytrend.related_topics()
#related_topic.values()

# Related Topics

In [ ]:
topT = related_topic['']['top']
topT.style.set_table_attributes("style='display:inline'").set_caption('Top Related Topics')

In [ ]:
risingT = related_topic['']['rising']
risingT.style.set_table_attributes("style='display:inline'").set_caption('Rising Related Topics')

## Keyword Suggestion
Google Trends can give you a list of keyword suggestions related to your primary keyword. In the example below, you will send a request to find suggestions for a keyword called “Business Intelligence.”

The suggestions method from pytrends will fetch keyword suggestions from Google Trends and return them in a data frame format.

In [ ]:
keywords = pytrend.suggestions(keyword='honda hrv')
df = pd.DataFrame(keywords)
print(df)

         mid       title            type
0  /m/07j3sv  Honda HR-V  Subcompact SUV

### Saving data - Category : Autos & Vehicles

In [ ]:
# Suggestion Keywords

In [ ]:
top.to_csv("TopKeywordsGT.csv")

In [ ]:
rising.to_csv("RisingKeywordsGT.csv")

In [ ]:
# Related Keyword

In [ ]:
topT.to_csv("TopRelatedKeywordsGT.csv")

In [ ]:
risingT.to_csv("RisingRelatedKeywordsGT.csv")